scalar Date

type User {
    id: ID!
    username: String!
    is_active: Boolean!
    displayName: String!
    created_at: Date!
    updated_at: Date!
    roles: [Role]!
}

input CreateUserInput {
    username: String!
    displayName: String!
    password: String!
}

input UpdateUserInput {
    username: String
    displayName: String
}